apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    id: c0905659
    app: nginx
    env: dev
  namespace: nginx-proxy
data:
  default.conf: |
    server {
      listen 80;

      location / {
        proxy_pass http://wp-service.wp.svc.cluster.local;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }
    }



