apiVersion: v1 
kind: Service
metadata:
  name: nginx-service
  labels:
    id: c0905659
    app: nginx
    env: dev
  namespace: nginx-proxy
spec:
  selector:
    id: c0905659
    app: nginx
    env: dev
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
  
