apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-config
  namespace: wp
  labels:
    id: c0905659
    app: wp
    env: dev
data:
  WORDPRESS_DB_HOST: db-service.db.svc.cluster.local
  WORDPRESS_DB_USER: wordpress
  WORDPRESS_DB_NAME: wordpress
