apiVersion: v1
kind: Service
metadata:
  name: wp-service
  labels:
    id: c0905659
    app: wp
    env: dev
  namespace: wp
spec:
  selector:
      id: c0905659
      app: wp
      env: dev
  ports:
    - port: 80
      targetPort: 80
