apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: db
  labels:
    id: c0905659
    app: db
    env: dev
data:
  MYSQL_PASSWORD: d29yZHByZXNzDQo=
  MYSQL_ROOT_PASSWORD: c29tZXdvcmRwcmVzcw0K
  